import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";

const RoobertRegular = localFont(
  {
      src: [
        {
          path: "../public/fonts/RoobertTRIALRegular.woff",
          weight: "400"
        }
      ],
      variable: "--RoobertRegular"
  }
)
const RoobertSemiBold = localFont(
  {
      src: [
        {
          path: "../public/fonts/RoobertTRIALSemiBold.woff",
          weight: "600"
        }
      ],
      variable: "--RoobertSemiBold"
  }
)

export const metadata: Metadata = {
  title: {
    default: "Skinstric",
    template: "Skinstric | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${RoobertRegular.variable} ${RoobertSemiBold.variable}`}>
      <body className="font-roobertReg">
        <Nav/>
        {children}
      </body>
    </html>
  );
}
