import IntroModule from '@/components/IntroModule';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Introduction",
    description: "Generated by create next app",
  };

const Page = () => {
    return (
        <div className='p-[32px] h-[calc(100vh-64px)] flex flex-col relative justify-between'>
            <div>
                <p className='uppercase font-roobertSemiBold text-main-black'>To start analysis</p>
            </div>
            <IntroModule/>
            <div className='h-[128px]'></div>
        </div>
    );
}

export default Page;
